### ISSUE TITLE
Benchmark report linked in README 404s

### ISSUE THREAD

**Issue by bitemyapp** [cgag/selecth#2]
https://github.com/cgag/selecth#differences-from-selecta

"Checkout this beautiful report generated by Bryan O'Sullivan amazing Criterion."

https://rawgit.com/cgag/selecth/master/report-2015.html

Edit: https://rawgit.com/cgag/selecth/master/reports/report-2015.html seems to work (moved to reports dir I think)

**Comment by cgag** [comment]
Thanks, the readme is way old, I think both this and selecta have gotten significantly faster since then, and selecta has totally rewritten his benchmarking suite, so I don't know if this is a fair comparison anymore.  I'm (very casually) working on getting them more in sync, I think I'll just get rid of the comparison until that's done.

**Comment by bitemyapp** [comment]
@cgag makes sense. I've been fortunate that `flake` has been updated since 2013 so my comparison in `blacktip` holds ^_^
